/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import java.util.ArrayList;

import gradle.components.inputs.Input;
import gradle.components.inputs.ListPasswordPage;
import gradle.components.inputs.SelectInput;
import gradle.components.outputs.HLine;
import gradle.components.outputs.Label;
import gradle.components.outputs.Space;
import gradle.pages.InputPage;
import gradle.pages.MainPage;
import models.DataPassword;
import models.PasswordStore;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            new MainPage("Main Page", 50).draw();
            DataPassword.loadCSVData();
            DataPassword.saveCSVData();


        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
